# Generated by Django 2.2.5 on 2019-12-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('toss_decision', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('dl_applied', models.IntegerField()),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=200)),
                ('umpire1', models.CharField(max_length=200)),
                ('umpire2', models.CharField(max_length=200)),
                ('umpire3', models.CharField(max_length=200)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='api.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='api.Team')),
                ('toss_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tosswinner', to='api.Team')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='api.Location')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='api.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('is_super_over', models.IntegerField()),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('dismissal_kind', models.CharField(max_length=200)),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batsman', to='api.Player')),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battingteam', to='api.Team')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowlingteam', to='api.Team')),
                ('fielder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fielder', to='api.Player')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Matches')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonstriker', to='api.Player')),
                ('player_dismissed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerdismissed', to='api.Player')),
            ],
        ),
    ]
