# Generated by Django 2.2.5 on 2019-12-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='player_of_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerofmatch', to='api.Player'),
        ),
    ]
