# Generated by Django 2.2.5 on 2019-12-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191229_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='dismissal_kind',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
