# Generated by Django 2.2.5 on 2019-12-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191229_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='dismissal_kind',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='fielder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fielder', to='api.Player'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='player_dismissed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerdismissed', to='api.Player'),
        ),
    ]
